### ISSUE TITLE
No module named 'send_whatsapp_message'!!

### ISSUE THREAD

**Issue by athrvvvv** [devnamdev2003/PC_Assistant#3]
Hello there, I have ran into an error!!??

![image](https://user-images.githubusercontent.com/98272709/209168855-26ab7d89-0b9a-4cf9-b0c5-5d65db3830fe.png)

Although, I searched module on pypi, I did'nt found it?? Also, there is no file named "send_text_message.py" What is solution to this? 

Sending love, athrv 😍

**Comment by devnamdev2003** [comment]
This is another python file.
and I uploaded it.
And first create an account on Sinch Application, because I am using sinch API to send a message through my python program.

So now you are happy 😊

**Comment by athrvvvv** [comment]
Yupp! Thanks dude 🤗

**Comment by athrvvvv** [comment]
and what about "send_whatsapp_message" module??
